export const reduxActions = {
    MODEL_SELECT_ACTION: 'SELECT_MODEL',
    ENGINE_SELECT_ACTION: 'SELECT_ENGINE',
    GEARBOX_SELECT_ACTION: 'SELECT_GEARBOX',
    COLOR_SELECT_ACTION: 'SELECT_COLOR',

    MODELS_SET_ACTION: 'SET_MODELS',
    ENGINES_SET_ACTION: 'SET_ENGINES',
    GEARBOXES_SET_ACTION: 'SET_GEARBOXES',
    COLORS_SET_ACTION: 'SET_COLORS',

    PRICES_SET_ACTION: 'SET_PRICES',
    COLORS_NAMES_SET_ACTION: 'SET_COLORS_NAMES'
};

export const defaultPayloadValues = {
    DEFAULT_EMPTY_VALUE: '-'
};
